### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by LiliwoL** [saeros/tumblrpost#1]
Hi,
i'm trying to use your script and after configuring and suscribing to TumblrAPI, i'm stucked with a 401 error. 
Do you have an diea if it's related to API? Do i need to laucnh your script from the url of the application i gave to TumblrAPI?

Best regards.
N.

**Comment by yonicsurny** [comment]
Hi,

Sorry for the delay in my response, I didn't get a notification about your message.

Did you provide the 4 keys in the config.json file?

![explore_api](https://cloud.githubusercontent.com/assets/562587/13945836/c18266fe-f010-11e5-8b58-a5146f821754.png)
You can get the values by following the "Explore API" link below the name of your app.

![console](https://cloud.githubusercontent.com/assets/562587/13945837/c1827518-f010-11e5-967a-6bdad66f09f6.png)
Once you have provided the 4 keys it should work as expected.

The url you provided in your application on TumblrAPI is just for information, it is not used by the script.

Regards,
Yonic
